server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
    # datasource:
    #     password: 12345edcba
    #     url: jdbc:mysql://localhost:3306/usuariodb?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    #     username: root
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: create-drop
            show_sql: true
            hbm2ddl.auto: create-drop
    h2:
        console:
            enabled: true
            path: /db
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer


    
   